; PlatformIO Project Configuration File
;
; ESP32-C6 + SCD41 CO2 Sensor with Zigbee

[env:esp32c6-zigbee]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf

board_build.flash_size = 4MB
board_build.partitions = zigbee.csv
board_upload.flash_size = 4MB

monitor_speed = 115200
upload_speed = 460800
